# example netlify.toml
[build]
  command = "yarn workspace frontend build"
  #functions = "netlify/functions"
  #publish = "apps/frontend/.next"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config

# Global environment variables (available in all contexts)
[build.environment]
  # Add global environment variables here
  DXP_URL = "https://app-ocxcmish122w0uprod.cms.optimizely.com/"
  SITE_DOMAIN = "optly-cms-demo-take5.vercel.app"
  OPTIMIZELY_CONTENTGRAPH_SECRET = "kxGv/PZ84FRll/ro9pVJgos8goZkMVPpOvoGq5UqSX3oCmol4bELFaFTwdgCy+t9"
  OPTIMIZELY_CONTENTGRAPH_APP_KEY = "nqrGFlTEoNs4XXGscBHvDHlMWZ3BQapgMUeAyZMCpLxJokjE"
  OPTIMIZELY_CONTENTGRAPH_SINGLE_KEY = "ezKe4JSOjtilFKfhfOJnGeeUslzNFLAAg4eMZzahJyYbnDgz"
  OPTIMIZELY_CONTENTGRAPH_GATEWAY = "https://cg.optimizely.com"
  OPTIMIZELY_CONTENTGRAPH_UPDATE_DELAY = "2000"
  NEXTAUTH_URL = "https://${SITE_DOMAIN}"
  NEXTAUTH_SECRET = "SECRET-${SITE_DOMAIN}-${DXP_URL}-${NODE_ENV}"
  DXP_DEBUG = "0"
  QUERY_LOG = "0"
  FRONTEND_PUBLISH_TOKEN = "optly-PUBLISH_TOKEN"
  NETLIFY_USE_YARN="true"